FileVersion = 1

[Project]
Name = "RayTracingInOneWeekendWithBeef"
StartupObject = "RayTracingWeekend.Program"
DefaultNamespace = "RayTracingWeekend"

[Configs.Release.Win64]
OptimizationLevel = "O3"
VectorizeLoops = true
VectorizeSLP = true
